import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

const claims = 'modules/claims/options/';

/** Original claims option labels, scopes, order and business URLs. */
export const claimsNavigation: ModuleOption[] = [
  option(
    'claims',
    'benefit',
    'Benefit Claim',
    '福利报销',
    'Car maintenance, personal allowance, mobile, optical and dental.',
    '车辆保养、个人津贴、手机、眼镜与牙科报销。',
    'individual',
    'requests',
    `${claims}benefit-claim.html`,
    'gift',
  ),
  option(
    'claims',
    'medical',
    'Medical Claim',
    '医疗报销',
    'GP clinic, specialist consultation, pharmacy and medication.',
    '普通门诊、专科诊疗、药房与药物报销。',
    'individual',
    'requests',
    `${claims}medical-claim.html`,
    'medical',
  ),
  option(
    'claims',
    'ot',
    'OT Claim',
    '加班报销',
    'Overtime meal allowance and night transport claims.',
    '加班餐费津贴与夜间交通报销。',
    'individual',
    'requests',
    `${claims}ot-claim.html`,
    'timer',
  ),
  option(
    'claims',
    'travel',
    'Travel Mileage',
    '出差里程',
    'Mileage, parking and toll receipt claims.',
    '里程、停车与过路费报销。',
    'individual',
    'requests',
    `${claims}travel-claim.html`,
    'car',
  ),
  option(
    'claims',
    'travel-request',
    'Travel Request',
    '出差申请',
    'Submit travel dates, destination and request details.',
    '填写出差日期、目的地与申请详情。',
    'individual',
    'requests',
    `${claims}travel-request.html`,
    'plane',
  ),
  option(
    'claims',
    'entertainment',
    'Entertainment',
    '招待费用',
    'Client dining and entertainment claims.',
    '客户用餐与招待费用报销。',
    'individual',
    'requests',
    `${claims}entertainment-claim.html`,
    'receipt',
  ),
  option(
    'claims',
    'advance',
    'Advance',
    '预支申请',
    'Request and review travel advances.',
    '申请与查看出差预支款。',
    'individual',
    'requests',
    `${claims}advance-claim.html`,
    'wallet',
  ),
  option(
    'claims',
    'expenses',
    'Expenses Claim',
    '费用报销',
    'Submit expense amounts, receipts and supporting details.',
    '填写费用金额、收据与相关资料。',
    'individual',
    'requests',
    `${claims}expenses-claim.html`,
    'receipt',
  ),
  option(
    'claims',
    'history',
    'Claim History',
    '报销历史',
    'Request history, status, details and workflows.',
    '申请历史、状态、详情与审批流程。',
    'individual',
    'records',
    `${claims}history.html`,
    'history',
  ),
  option(
    'claims',
    'summary',
    'Claim Summary',
    '报销汇总',
    'Review claim totals and category breakdowns.',
    '查看报销总额与类别明细。',
    'individual',
    'reports',
    `${claims}summary.html`,
    'chart',
  ),
  option(
    'claims',
    'travel-calendar',
    'My travel',
    '我的出差',
    'Personal travel calendar and scheduled trip details.',
    '个人出差日历与行程详情。',
    'individual',
    'planning',
    'modules/claims/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'claims',
    'benefit-highlight',
    'Benefit Highlight',
    '福利重点',
    'Review staff benefit claims and analysis.',
    '查看员工福利报销与分析。',
    'team',
    'reports',
    `${claims}benefit-highlight.html`,
    'chart',
  ),
  option(
    'claims',
    'staff-entitlement',
    'Staff Benefit Entitlement',
    '员工福利额度',
    'Review staff benefit entitlement, usage and balance.',
    '查看员工福利额度、用量与余额。',
    'team',
    'information',
    `${claims}staff-entitlement.html`,
    'users',
  ),
  option(
    'claims',
    'expense-highlight',
    'Expense Highlight',
    '费用重点',
    'Review expense claim indicators and analysis.',
    '查看费用报销指标与分析。',
    'team',
    'reports',
    `${claims}expenses-highlight.html`,
    'chart',
  ),
  option(
    'claims',
    'staff-summary',
    'Staff Claim Summary',
    '员工报销汇总',
    'Review claim summaries across your staff.',
    '查看员工报销汇总。',
    'team',
    'reports',
    `${claims}staff-summary.html`,
    'clipboard',
  ),
  option(
    'claims',
    'approval',
    'Pending Approval',
    '待审批',
    'Staff claims awaiting review, with full request details.',
    '待审批的员工报销与完整申请详情。',
    'team',
    'approvals',
    `${claims}pending-approval.html`,
    'check',
  ),
  option(
    'claims',
    'team-calendar',
    'Staff travel calendar',
    '员工出差日历',
    'Filter staff travel and review scheduled trips.',
    '筛选员工出差并查看行程。',
    'team',
    'planning',
    'modules/claims/index.html?webView=details&scope=team',
    'calendar',
  ),
];
