import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

const workplace = 'modules/admin/options/';

/** Original admin option labels, scopes, order and business URLs. */
export const adminNavigation: ModuleOption[] = [
  option(
    'admin',
    'news',
    'News',
    '公告',
    'Company news, announcements and article details.',
    '公司新闻、公告与文章详情。',
    'individual',
    'information',
    `${workplace}news.html`,
    'file',
  ),
  option(
    'admin',
    'book-resource',
    'Book Resource',
    '预约资源',
    'Choose resources, dates and booking details.',
    '选择资源、日期与预约详情。',
    'individual',
    'requests',
    `${workplace}book-resource.html`,
    'calendar',
  ),
  option(
    'admin',
    'letter-request',
    'Letter Request',
    '信件申请',
    'Request HR letters with the required information.',
    '填写所需资料以申请人事信件。',
    'individual',
    'requests',
    `${workplace}letter-request.html`,
    'file-plus',
  ),
  option(
    'admin',
    'guest-visit',
    'Guest Visit',
    '访客登记',
    'Visitor details, visit schedules and visit requests.',
    '访客资料、来访时间与来访申请。',
    'individual',
    'requests',
    `${workplace}guest-visit.html`,
    'user-check',
  ),
  option(
    'admin',
    'inventory-request',
    'Inventory Request',
    '物品申请',
    'Select inventory items, quantities and request details.',
    '选择物品、数量与申请详情。',
    'individual',
    'requests',
    `${workplace}inventory-request.html?scope=individual`,
    'package',
  ),
  option(
    'admin',
    'policy-sop',
    'Policy / SOP',
    '政策与标准流程',
    'Read company policies and standard operating procedures.',
    '阅读公司政策与标准作业流程。',
    'individual',
    'information',
    `${workplace}policy-sop.html`,
    'shield',
  ),
  option(
    'admin',
    'history',
    'History',
    '历史记录',
    'Resource, letter, visitor and inventory request history.',
    '资源、信件、访客与物品申请历史。',
    'individual',
    'records',
    `${workplace}history.html`,
    'history',
  ),
  option(
    'admin',
    'calendar',
    'Calendar',
    '日历',
    'Workplace bookings, visits and scheduled events.',
    '行政资源预约、来访与日程事项。',
    'individual',
    'planning',
    'modules/admin/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'admin',
    'pending-approval',
    'Pending Approval',
    '待审批',
    'Workplace requests awaiting review.',
    '待审批的行政申请。',
    'team',
    'approvals',
    `${workplace}pending-approval.html?scope=team`,
    'check',
  ),
  option(
    'admin',
    'asset-highlight',
    'Asset Highlight',
    '资产重点',
    'Review resource and asset information.',
    '查看资源与资产资料。',
    'team',
    'reports',
    `${workplace}asset-highlight.html?scope=team`,
    'package',
  ),
];
