import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

/** Original leave option labels, scopes, order and business URLs. */
export const leaveNavigation: ModuleOption[] = [
  option(
    'leave',
    'leave',
    'Leave',
    '请假',
    'Choose a leave type and complete the leave application.',
    '选择假期类别并填写请假申请。',
    'individual',
    'requests',
    'leave.html?webView=details&view=apply',
    'calendar',
  ),
  option(
    'leave',
    'credit',
    'Leave Credit',
    '补休申请',
    'Apply for leave credit with its date, hours and reason.',
    '填写日期、时数与原因以申请补休。',
    'individual',
    'requests',
    'leave.html?webView=details&webSection=viewCreditLeaveForm',
    'file-plus',
  ),
  option(
    'leave',
    'time-off',
    'Time Off',
    '短时请假',
    'Apply for time off with the original approval workflow.',
    '申请短时请假并沿用原有审批流程。',
    'individual',
    'requests',
    'leave.html?webView=details&webSection=viewApplyOffTimeForm',
    'clock',
  ),
  option(
    'leave',
    'history',
    'History',
    '历史记录',
    'Leave, credit leave and time off request history.',
    '请假、补休与短时请假申请历史。',
    'individual',
    'records',
    'leave.html?webView=details&view=history',
    'history',
  ),
  option(
    'leave',
    'credit-records',
    'Credit Leave',
    '补休记录',
    'Review credited leave and existing credit requests.',
    '查看已获补休与补休申请。',
    'individual',
    'records',
    'leave.html?webView=details&view=credit',
    'clipboard',
  ),
  option(
    'leave',
    'calendar',
    'My Leave Calendar',
    '个人请假日历',
    'Leave dates, holidays and calendar record details.',
    '请假日期、节假日与日历记录详情。',
    'individual',
    'planning',
    'leave.html?webView=details&view=my-calendar',
    'calendar',
  ),
  option(
    'leave',
    'balance',
    'Leave Entitlements & Types',
    '假期额度与类别',
    'Review entitled, taken, pending and available leave.',
    '查看假期额度、已使用、待审批与可用假期。',
    'individual',
    'information',
    'leave.html?webView=details&view=apply',
    'file',
  ),
  option(
    'leave',
    'highlight',
    'Leave Highlight',
    '假期重点',
    'Leave indicators, charts, trends and staff analysis.',
    '假期指标、图表、趋势与员工分析。',
    'team',
    'reports',
    'leave.html?webView=details&mode=team&view=highlight',
    'chart',
  ),
  option(
    'leave',
    'entitlement',
    'Staff Leave Entitlement',
    '员工假期额度',
    'Review staff leave entitlement and balances.',
    '查看员工假期额度与余额。',
    'team',
    'information',
    'leave.html?webView=details&mode=team&view=entitlement',
    'users',
  ),
  option(
    'leave',
    'approvals',
    'Pending Approval',
    '待审批',
    'Review leave, credit leave and time off requests.',
    '审批请假、补休与短时请假申请。',
    'team',
    'approvals',
    'leave.html?webView=details&mode=team&view=approvals',
    'check',
  ),
  option(
    'leave',
    'team-calendar',
    'Team Leave Calendar',
    '团队请假日历',
    'Staff leave dates and daily team leave details.',
    '查看员工请假日期与每日团队请假详情。',
    'team',
    'planning',
    'leave.html?webView=details&mode=team&view=team-calendar',
    'calendar',
  ),
];
