import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

/** Original profile option labels, scopes, order and business URLs. */
export const profileNavigation: ModuleOption[] = [
  option(
    'profile',
    'work',
    'Work',
    '工作资料',
    'Employee ID, appointment, department and employment details.',
    '员工编号、职位、部门与任职详情。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-work',
    'briefcase',
  ),
  option(
    'profile',
    'personal',
    'Personal & Family',
    '个人与家庭',
    'Personal particulars, spouse, children and family information.',
    '个人资料、配偶、子女与家庭信息。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-personal',
    'user',
  ),
  option(
    'profile',
    'contact',
    'Contact & Address',
    '联系方式与地址',
    'Contact numbers, addresses and emergency contacts.',
    '电话号码、地址与紧急联系人。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-contact',
    'pin',
  ),
  option(
    'profile',
    'qualification',
    'Qualification',
    '学历与资格',
    'Education and qualification records.',
    '教育与资格记录。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-education',
    'award',
  ),
  option(
    'profile',
    'payroll',
    'Payroll & Tax',
    '薪资与税务',
    'Bank, statutory, payroll and tax information.',
    '银行、法定缴纳、薪资与税务资料。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-finance',
    'wallet',
  ),
  option(
    'profile',
    'career',
    'Career',
    '职业经历',
    'Career and employment history.',
    '职业与任职历史。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-career',
    'briefcase',
  ),
  option(
    'profile',
    'performance',
    'Performance',
    '绩效',
    'Performance assessments and their details.',
    '绩效评估与详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-performance',
    'chart',
  ),
  option(
    'profile',
    'competencies',
    'Competencies',
    '能力',
    'Competency assessments and recorded skills.',
    '能力评估与技能记录。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-competency',
    'award',
  ),
  option(
    'profile',
    'training',
    'Training',
    '培训',
    'Training courses, dates and training records.',
    '培训课程、日期与记录。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-training',
    'book',
  ),
  option(
    'profile',
    'assets',
    'Assets',
    '资产',
    'Assigned assets and custody details.',
    '领用资产与保管详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-assets',
    'package',
  ),
  option(
    'profile',
    'hr-letters',
    'HR Letters',
    '人事信件',
    'HR letters and letter document details.',
    '人事信件与文件详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-letters',
    'file',
  ),
  option(
    'profile',
    'disciplinary',
    'Disciplinary',
    '纪律记录',
    'Disciplinary records and related details.',
    '纪律记录与相关详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-compliance',
    'shield',
  ),
  option(
    'profile',
    'view-jd',
    'View JD',
    '查看岗位说明',
    'Your job description, responsibilities and requirements.',
    '个人岗位说明、职责与要求。',
    'individual',
    'information',
    'me.html?webView=details&webAction=profile-jd',
    'file',
  ),
  option(
    'profile',
    'bonus-history',
    'Bonus History',
    '奖金历史',
    'Historical bonus payments and their details.',
    '往期奖金与明细。',
    'individual',
    'records',
    'bonus-history.html',
    'wallet',
  ),
  option(
    'profile',
    'salary-history',
    'Salary History',
    '薪资历史',
    'Salary changes and historical salary records.',
    '薪资调整与往期薪资记录。',
    'individual',
    'records',
    'salary-history.html',
    'history',
  ),
  option(
    'profile',
    'change-request',
    'Change Request',
    '资料更改申请',
    'Request changes to personal and employment information.',
    '申请修改个人与任职资料。',
    'individual',
    'requests',
    'change-request.html',
    'file-plus',
  ),
  option(
    'profile',
    'work-behaviour',
    'Work Behaviour Trend',
    '工作行为趋势',
    'Work behaviour indicators and trends.',
    '工作行为指标与趋势。',
    'individual',
    'reports',
    'work-behaviour.html',
    'chart',
  ),
  option(
    'profile',
    'subordinates',
    'Subordinates',
    '下属员工',
    'Review your reporting staff and their information.',
    '查看直属员工与相关资料。',
    'team',
    'information',
    'subordinates.html',
    'users',
  ),
];
