import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

const payroll = 'modules/payroll/options/';

/** Original payroll option labels, scopes, order and business URLs. */
export const payrollNavigation: ModuleOption[] = [
  option(
    'payroll',
    'prior-pay',
    'Prior Pay Data',
    '往期薪资数据',
    'Previous payroll records.',
    '往期薪资记录。',
    'individual',
    'records',
    `${payroll}prior-pay-data.html`,
    'history',
  ),
  option(
    'payroll',
    'tax-relief',
    'Tax Relief',
    '税务减免',
    'Personal tax relief records.',
    '个人税务减免记录。',
    'individual',
    'requests',
    `${payroll}tax-relief-request.html`,
    'file',
  ),
  option(
    'payroll',
    'deduction',
    'Deduction Request',
    '扣款申请',
    'Submit a payroll deduction.',
    '提交薪资扣款申请。',
    'individual',
    'requests',
    `${payroll}deduction-request.html`,
    'file-plus',
  ),
  option(
    'payroll',
    'payslip',
    'Payslip',
    '工资单',
    'Monthly salary statements.',
    '每月薪资明细。',
    'individual',
    'records',
    `${payroll}payslip.html`,
    'wallet',
  ),
  option(
    'payroll',
    'ea',
    'EA',
    'EA 年度税务表',
    'Annual tax statement.',
    '年度税务报表。',
    'individual',
    'records',
    `${payroll}ea-form.html`,
    'file',
  ),
  option(
    'payroll',
    'history',
    'History',
    '历史记录',
    'Payroll activity records.',
    '薪资活动记录。',
    'individual',
    'records',
    `${payroll}history.html`,
    'history',
  ),
  option(
    'payroll',
    'tax-relief',
    'Tax Relief',
    '税务减免',
    'Review and approve staff tax relief claims.',
    '查看并审批员工税务减免申请。',
    'team',
    'approvals',
    `${payroll}tax-relief.html`,
    'file',
  ),
  option(
    'payroll',
    'pending',
    'Pending Approval',
    '待审批',
    'Tax relief and deduction requests awaiting review.',
    '待审批的税务减免与扣款申请。',
    'team',
    'approvals',
    `${payroll}pending-approval.html`,
    'check',
  ),
];
