import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

const career = 'modules/employee-career/options/';

/** Original employee-career option labels, scopes, order and business URLs. */
export const employeeCareerNavigation: ModuleOption[] = [
  option(
    'employee-career',
    'feedback',
    'Feedback',
    '反馈',
    'Submit employee feedback and review its history.',
    '提交员工反馈并查看历史。',
    'individual',
    'requests',
    `${career}individual/feedback.html`,
    'message',
  ),
  option(
    'employee-career',
    'whereabout',
    'Whereabout',
    '行踪',
    'Record your location, dates and whereabouts.',
    '记录个人地点、日期与行踪。',
    'individual',
    'requests',
    `${career}individual/whereabout.html`,
    'pin',
  ),
  option(
    'employee-career',
    'my-event',
    'My Event',
    '个人事项',
    'Submit and review your employee events.',
    '提交并查看个人员工事项。',
    'individual',
    'requests',
    `${career}individual/my-event.html`,
    'calendar',
  ),
  option(
    'employee-career',
    'history',
    'History',
    '历史记录',
    'Feedback, whereabouts and employee event history.',
    '反馈、行踪与员工事项历史。',
    'individual',
    'records',
    `${career}history.html`,
    'history',
  ),
  option(
    'employee-career',
    'onboard-activity',
    'Onboard Activity',
    '入职活动',
    'Onboarding activity information.',
    '个人入职活动资料。',
    'individual',
    'planning',
    `${career}individual/onboard-activity.html`,
    'clipboard',
  ),
  option(
    'employee-career',
    'confirm-new-user',
    'Confirm New User',
    '确认新用户',
    'Review new users and their confirmation details.',
    '查看新用户与确认详情。',
    'team',
    'approvals',
    `${career}team/confirm-new-user.html`,
    'user-check',
  ),
  option(
    'employee-career',
    'staff-list',
    'Staff List',
    '员工列表',
    'Staff directory, employee cards and profile information.',
    '员工通讯录、员工卡片与资料。',
    'team',
    'information',
    `${career}team/staff-list.html`,
    'users',
  ),
  option(
    'employee-career',
    'manpower-stats',
    'Manpower Stats',
    '人力统计',
    'Review headcount and manpower statistics.',
    '查看人数与人力统计。',
    'team',
    'reports',
    `${career}team/manpower-stats.html`,
    'chart',
  ),
  option(
    'employee-career',
    'confirm-staff',
    'Confirm Staff',
    '员工转正',
    'Staff confirmation reviews and decisions.',
    '员工转正评估与决定。',
    'team',
    'approvals',
    `${career}team/confirm-staff.html`,
    'user-check',
  ),
  option(
    'employee-career',
    'staff-exit',
    'Staff Exit',
    '员工离职',
    'Review staff exits and exit details.',
    '查看员工离职与详情。',
    'team',
    'records',
    `${career}team/staff-exit.html`,
    'users',
  ),
  option(
    'employee-career',
    'staff-request',
    'Staff Request',
    '员工申请',
    'Manage staff requests and their workflows.',
    '管理员工申请与审批流程。',
    'team',
    'requests',
    `${career}team/staff-request.html`,
    'file-plus',
  ),
  option(
    'employee-career',
    'staff-attrition',
    'Staff Attrition',
    '员工流失',
    'Review staff attrition indicators and analysis.',
    '查看员工流失指标与分析。',
    'team',
    'reports',
    `${career}team/staff-attrition.html`,
    'chart',
  ),
  option(
    'employee-career',
    'staff-retention',
    'Staff Retention',
    '员工留任',
    'Review staff retention information and analysis.',
    '查看员工留任资料与分析。',
    'team',
    'reports',
    `${career}team/staff-retention.html`,
    'users',
  ),
  option(
    'employee-career',
    'staff-whereabout',
    'Staff Whereabout',
    '员工行踪',
    'Review staff whereabouts and location records.',
    '查看员工行踪与地点记录。',
    'team',
    'records',
    `${career}team/staff-whereabout.html`,
    'pin',
  ),
  option(
    'employee-career',
    'staff-events',
    'Staff Events',
    '员工事项',
    'Review employee events across the team.',
    '查看团队员工事项。',
    'team',
    'records',
    `${career}team/staff-events.html`,
    'calendar',
  ),
  option(
    'employee-career',
    'staff-feedback',
    'Staff Feedback',
    '员工反馈',
    'Review staff feedback records and responses.',
    '查看员工反馈记录与回复。',
    'team',
    'records',
    `${career}team/staff-feedback.html`,
    'message',
  ),
  option(
    'employee-career',
    'key-staff-nomination',
    'Key Staff Nomination',
    '关键员工提名',
    'Nominate and review key staff.',
    '提名与查看关键员工。',
    'team',
    'requests',
    `${career}team/key-staff-nomination.html`,
    'award',
  ),
  option(
    'employee-career',
    'staff-engagement',
    'Staff Engagement',
    '员工参与度',
    'Staff engagement information.',
    '员工参与度资料。',
    'team',
    'reports',
    `${career}team/staff-engagement.html`,
    'users',
  ),
  option(
    'employee-career',
    'staff-onboard',
    'Staff Onboard',
    '员工入职',
    'Staff onboarding information.',
    '员工入职资料。',
    'team',
    'planning',
    `${career}team/staff-onboard.html`,
    'user-check',
  ),
];
