export type ModuleScope = 'individual' | 'team' | 'shared';
export type ModuleGroup =
  | 'requests'
  | 'records'
  | 'approvals'
  | 'reports'
  | 'planning'
  | 'information';

export interface ModuleOption {
  id: string;
  moduleId: string;
  title: string;
  titleZh: string;
  description: string;
  descriptionZh: string;
  scope: ModuleScope;
  group: ModuleGroup;
  path: string;
  icon: string;
}

export const moduleOverviewPaths: Record<string, string> = {
  attendance: 'modules/attendance/index.html',
  leave: 'leave.html',
  claims: 'modules/claims/index.html',
  payroll: 'modules/payroll/index.html',
  'employee-career': 'modules/employee-career/index.html',
  'project-task': 'modules/project-task/index.html',
  admin: 'modules/admin/index.html',
  profile: 'me.html',
};

function option(
  moduleId: string,
  id: string,
  title: string,
  titleZh: string,
  description: string,
  descriptionZh: string,
  scope: ModuleScope,
  group: ModuleGroup,
  path: string,
  icon: string,
): ModuleOption {
  return {
    id: `${moduleId}-${scope}-${id}`,
    moduleId,
    title,
    titleZh,
    description,
    descriptionZh,
    scope,
    group,
    path,
    icon,
  };
}

const attendance = 'modules/attendance/options/';
const claims = 'modules/claims/options/';
const payroll = 'modules/payroll/options/';
const career = 'modules/employee-career/options/';
const project = 'modules/project-task/options/';
const workplace = 'modules/admin/options/';

/**
 * Menu labels and destinations are transcribed from the immutable mobile source.
 * Detailed forms, categories, filters and workflows stay inside their real pages.
 * webView=details keeps a dashboard's calendar and analysis available as a document.
 */
export const moduleNavigation: ModuleOption[] = [
  option(
    'attendance',
    'clocking',
    'Clocking',
    '打卡',
    'Clock in and out, including location and remarks.',
    '上班与下班打卡，填写地点与备注。',
    'individual',
    'requests',
    `${attendance}clocking.html`,
    'clock',
  ),
  option(
    'attendance',
    'attendance',
    'Attendance',
    '考勤',
    'Daily attendance, work hours and attendance advice.',
    '每日考勤、工作时数与考勤反馈。',
    'individual',
    'records',
    `${attendance}attendance.html`,
    'clipboard',
  ),
  option(
    'attendance',
    'overtime',
    'Overtime',
    '加班',
    'Overtime plans, final requests and history.',
    '加班计划、最终加班申请与历史。',
    'individual',
    'requests',
    `${attendance}overtime.html`,
    'timer',
  ),
  option(
    'attendance',
    'hours-summary',
    'Hours Summary',
    '时数汇总',
    'Review your work and overtime hours.',
    '查看个人工作与加班时数。',
    'individual',
    'reports',
    `${attendance}hours-summary.html`,
    'chart',
  ),
  option(
    'attendance',
    'history',
    'History',
    '历史记录',
    'Attendance requests, details and workflow status.',
    '考勤申请、详情与审批流程状态。',
    'individual',
    'records',
    `${attendance}history.html`,
    'history',
  ),
  option(
    'attendance',
    'feedback',
    'Pending Attendance Feedback',
    '待处理考勤反馈',
    'Review and respond to attendance feedback.',
    '查看并处理考勤反馈。',
    'individual',
    'requests',
    `${attendance}feedback-history.html`,
    'message',
  ),
  option(
    'attendance',
    'clocking-history',
    'Clocking History',
    '打卡记录',
    'Submitted, resubmit, approved and rejected clocking records.',
    '已提交、需重新提交、已批准与已拒绝的打卡记录。',
    'individual',
    'records',
    `${attendance}clocking-history.html`,
    'history',
  ),
  option(
    'attendance',
    'calendar',
    'My Schedule',
    '我的排班',
    'Your calendar, shift and overtime details.',
    '查看个人日历、班次与加班安排。',
    'individual',
    'planning',
    'modules/attendance/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'attendance',
    'shift-plan',
    'Shift Plan',
    '排班计划',
    'Plan work shifts, leave and nonworking days.',
    '安排工作班次、请假与休息日。',
    'team',
    'planning',
    `${attendance}shift-plan.html`,
    'calendar',
  ),
  option(
    'attendance',
    'ot-plan',
    'OT Plan',
    '加班计划',
    'Plan staff overtime and review planned hours.',
    '安排员工加班并查看计划时数。',
    'team',
    'planning',
    `${attendance}ot-plan.html`,
    'timer',
  ),
  option(
    'attendance',
    'daily-ot',
    'Daily OT',
    '每日加班',
    'Review daily overtime and final OT details.',
    '查看每日加班与最终加班详情。',
    'team',
    'records',
    `${attendance}daily-ot.html`,
    'clock',
  ),
  option(
    'attendance',
    'daily-manpower',
    'Daily Manpower',
    '每日人力',
    'Scheduled, present, absent and overtime manpower.',
    '计划出勤、实际出勤、缺勤与加班人力。',
    'team',
    'reports',
    `${attendance}daily-manpower.html`,
    'users',
  ),
  option(
    'attendance',
    'work-hour-violation',
    'Work Hour Violation',
    '工时违规',
    'Review staff work hour violations.',
    '查看员工工时违规情况。',
    'team',
    'reports',
    `${attendance}work-hour-violation.html`,
    'shield',
  ),
  option(
    'attendance',
    'clocking-summary',
    'Clocking Summary',
    '打卡汇总',
    'Staff clocking and exception summaries.',
    '员工打卡与异常汇总。',
    'team',
    'reports',
    `${attendance}clocking-summary.html`,
    'clipboard',
  ),
  option(
    'attendance',
    'staff-attendance',
    'Staff Attendance',
    '员工考勤',
    'Review employee attendance records and details.',
    '查看员工考勤记录与详情。',
    'team',
    'records',
    `${attendance}staff-attendance.html`,
    'users',
  ),
  option(
    'attendance',
    'staff-hours-summary',
    'Staff Hours Summary',
    '员工时数汇总',
    'Staff work, overtime and leave hours.',
    '员工工作、加班与请假时数。',
    'team',
    'reports',
    `${attendance}staff-hours-summary.html`,
    'chart',
  ),
  option(
    'attendance',
    'attendance-highlight',
    'Attendance Highlight',
    '考勤重点',
    'Attendance indicators, trends and analysis.',
    '考勤指标、趋势与分析。',
    'team',
    'reports',
    `${attendance}attendance-highlight.html`,
    'chart',
  ),
  option(
    'attendance',
    'overtime-highlight',
    'Overtime Highlight',
    '加班重点',
    'Overtime indicators and staff analysis.',
    '加班指标与员工分析。',
    'team',
    'reports',
    `${attendance}overtime-highlight.html`,
    'chart',
  ),
  option(
    'attendance',
    'overtime-costing',
    'Overtime Costing',
    '加班成本',
    'Review overtime costs and breakdowns.',
    '查看加班成本与分类明细。',
    'team',
    'reports',
    `${attendance}overtime-costing.html`,
    'wallet',
  ),
  option(
    'attendance',
    'attendance-performance',
    'Attendance Performance',
    '考勤表现',
    'Staff attendance performance and trends.',
    '员工考勤表现与趋势。',
    'team',
    'reports',
    `${attendance}attendance-performance.html`,
    'chart',
  ),
  option(
    'attendance',
    'hours-costing',
    'Hours Costing',
    '工时成本',
    'Review work hour costs and breakdowns.',
    '查看工时成本与分类明细。',
    'team',
    'reports',
    `${attendance}hours-costing.html`,
    'wallet',
  ),
  option(
    'attendance',
    'pending-approval',
    'Pending Approval',
    '待审批',
    'OT Plan Request, Final OT Request and Attendance Feedback.',
    '加班计划申请、最终加班申请与考勤反馈。',
    'team',
    'approvals',
    `${attendance}team.html?webView=details&view=approvals&tab=ot_plan`,
    'check',
  ),
  option(
    'attendance',
    'verification',
    'Attendance Verification',
    '考勤核实',
    'Clocking exceptions and feedback audits.',
    '打卡异常与考勤反馈核查。',
    'team',
    'approvals',
    `${attendance}team.html?webView=details&view=verification`,
    'shield',
  ),
  option(
    'attendance',
    'team-overview',
    'Team Overview',
    '团队概览',
    'Scheduled to work, planned OT, present and no show.',
    '计划出勤、计划加班、实际出勤与未到岗员工。',
    'team',
    'information',
    `${attendance}team.html?webView=details&scope=team`,
    'users',
  ),

  option(
    'leave',
    'leave',
    'Leave',
    '请假',
    'Choose a leave type and complete the leave application.',
    '选择假期类别并填写请假申请。',
    'individual',
    'requests',
    'leave.html?webView=details&view=apply',
    'calendar',
  ),
  option(
    'leave',
    'credit',
    'Leave Credit',
    '补休申请',
    'Apply for leave credit with its date, hours and reason.',
    '填写日期、时数与原因以申请补休。',
    'individual',
    'requests',
    'leave.html?webView=details&webSection=viewCreditLeaveForm',
    'file-plus',
  ),
  option(
    'leave',
    'time-off',
    'Time Off',
    '短时请假',
    'Apply for time off with the original approval workflow.',
    '申请短时请假并沿用原有审批流程。',
    'individual',
    'requests',
    'leave.html?webView=details&webSection=viewApplyOffTimeForm',
    'clock',
  ),
  option(
    'leave',
    'history',
    'History',
    '历史记录',
    'Leave, credit leave and time off request history.',
    '请假、补休与短时请假申请历史。',
    'individual',
    'records',
    'leave.html?webView=details&view=history',
    'history',
  ),
  option(
    'leave',
    'credit-records',
    'Credit Leave',
    '补休记录',
    'Review credited leave and existing credit requests.',
    '查看已获补休与补休申请。',
    'individual',
    'records',
    'leave.html?webView=details&view=credit',
    'clipboard',
  ),
  option(
    'leave',
    'calendar',
    'My Leave Calendar',
    '个人请假日历',
    'Leave dates, holidays and calendar record details.',
    '请假日期、节假日与日历记录详情。',
    'individual',
    'planning',
    'leave.html?webView=details&view=my-calendar',
    'calendar',
  ),
  option(
    'leave',
    'balance',
    'Leave Entitlements & Types',
    '假期额度与类别',
    'Review entitled, taken, pending and available leave.',
    '查看假期额度、已使用、待审批与可用假期。',
    'individual',
    'information',
    'leave.html?webView=details&view=apply',
    'file',
  ),
  option(
    'leave',
    'highlight',
    'Leave Highlight',
    '假期重点',
    'Leave indicators, charts, trends and staff analysis.',
    '假期指标、图表、趋势与员工分析。',
    'team',
    'reports',
    'leave.html?webView=details&mode=team&view=highlight',
    'chart',
  ),
  option(
    'leave',
    'entitlement',
    'Staff Leave Entitlement',
    '员工假期额度',
    'Review staff leave entitlement and balances.',
    '查看员工假期额度与余额。',
    'team',
    'information',
    'leave.html?webView=details&mode=team&view=entitlement',
    'users',
  ),
  option(
    'leave',
    'approvals',
    'Pending Approval',
    '待审批',
    'Review leave, credit leave and time off requests.',
    '审批请假、补休与短时请假申请。',
    'team',
    'approvals',
    'leave.html?webView=details&mode=team&view=approvals',
    'check',
  ),
  option(
    'leave',
    'team-calendar',
    'Team Leave Calendar',
    '团队请假日历',
    'Staff leave dates and daily team leave details.',
    '查看员工请假日期与每日团队请假详情。',
    'team',
    'planning',
    'leave.html?webView=details&mode=team&view=team-calendar',
    'calendar',
  ),

  option(
    'claims',
    'benefit',
    'Benefit Claim',
    '福利报销',
    'Car maintenance, personal allowance, mobile, optical and dental.',
    '车辆保养、个人津贴、手机、眼镜与牙科报销。',
    'individual',
    'requests',
    `${claims}benefit-claim.html`,
    'gift',
  ),
  option(
    'claims',
    'medical',
    'Medical Claim',
    '医疗报销',
    'GP clinic, specialist consultation, pharmacy and medication.',
    '普通门诊、专科诊疗、药房与药物报销。',
    'individual',
    'requests',
    `${claims}medical-claim.html`,
    'medical',
  ),
  option(
    'claims',
    'ot',
    'OT Claim',
    '加班报销',
    'Overtime meal allowance and night transport claims.',
    '加班餐费津贴与夜间交通报销。',
    'individual',
    'requests',
    `${claims}ot-claim.html`,
    'timer',
  ),
  option(
    'claims',
    'travel',
    'Travel Mileage',
    '出差里程',
    'Mileage, parking and toll receipt claims.',
    '里程、停车与过路费报销。',
    'individual',
    'requests',
    `${claims}travel-claim.html`,
    'car',
  ),
  option(
    'claims',
    'travel-request',
    'Travel Request',
    '出差申请',
    'Submit travel dates, destination and request details.',
    '填写出差日期、目的地与申请详情。',
    'individual',
    'requests',
    `${claims}travel-request.html`,
    'plane',
  ),
  option(
    'claims',
    'entertainment',
    'Entertainment',
    '招待费用',
    'Client dining and entertainment claims.',
    '客户用餐与招待费用报销。',
    'individual',
    'requests',
    `${claims}entertainment-claim.html`,
    'receipt',
  ),
  option(
    'claims',
    'advance',
    'Advance',
    '预支申请',
    'Request and review travel advances.',
    '申请与查看出差预支款。',
    'individual',
    'requests',
    `${claims}advance-claim.html`,
    'wallet',
  ),
  option(
    'claims',
    'expenses',
    'Expenses Claim',
    '费用报销',
    'Submit expense amounts, receipts and supporting details.',
    '填写费用金额、收据与相关资料。',
    'individual',
    'requests',
    `${claims}expenses-claim.html`,
    'receipt',
  ),
  option(
    'claims',
    'history',
    'Claim History',
    '报销历史',
    'Request history, status, details and workflows.',
    '申请历史、状态、详情与审批流程。',
    'individual',
    'records',
    `${claims}history.html`,
    'history',
  ),
  option(
    'claims',
    'summary',
    'Claim Summary',
    '报销汇总',
    'Review claim totals and category breakdowns.',
    '查看报销总额与类别明细。',
    'individual',
    'reports',
    `${claims}summary.html`,
    'chart',
  ),
  option(
    'claims',
    'travel-calendar',
    'My travel',
    '我的出差',
    'Personal travel calendar and scheduled trip details.',
    '个人出差日历与行程详情。',
    'individual',
    'planning',
    'modules/claims/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'claims',
    'benefit-highlight',
    'Benefit Highlight',
    '福利重点',
    'Review staff benefit claims and analysis.',
    '查看员工福利报销与分析。',
    'team',
    'reports',
    `${claims}benefit-highlight.html`,
    'chart',
  ),
  option(
    'claims',
    'staff-entitlement',
    'Staff Benefit Entitlement',
    '员工福利额度',
    'Review staff benefit entitlement, usage and balance.',
    '查看员工福利额度、用量与余额。',
    'team',
    'information',
    `${claims}staff-entitlement.html`,
    'users',
  ),
  option(
    'claims',
    'expense-highlight',
    'Expense Highlight',
    '费用重点',
    'Review expense claim indicators and analysis.',
    '查看费用报销指标与分析。',
    'team',
    'reports',
    `${claims}expenses-highlight.html`,
    'chart',
  ),
  option(
    'claims',
    'staff-summary',
    'Staff Claim Summary',
    '员工报销汇总',
    'Review claim summaries across your staff.',
    '查看员工报销汇总。',
    'team',
    'reports',
    `${claims}staff-summary.html`,
    'clipboard',
  ),
  option(
    'claims',
    'approval',
    'Pending Approval',
    '待审批',
    'Staff claims awaiting review, with full request details.',
    '待审批的员工报销与完整申请详情。',
    'team',
    'approvals',
    `${claims}pending-approval.html`,
    'check',
  ),
  option(
    'claims',
    'team-calendar',
    'Staff travel calendar',
    '员工出差日历',
    'Filter staff travel and review scheduled trips.',
    '筛选员工出差并查看行程。',
    'team',
    'planning',
    'modules/claims/index.html?webView=details&scope=team',
    'calendar',
  ),

  option(
    'payroll',
    'prior-pay',
    'Prior Pay Data',
    '往期薪资数据',
    'Previous payroll records.',
    '往期薪资记录。',
    'individual',
    'records',
    `${payroll}prior-pay-data.html`,
    'history',
  ),
  option(
    'payroll',
    'tax-relief',
    'Tax Relief',
    '税务减免',
    'Personal tax relief records.',
    '个人税务减免记录。',
    'individual',
    'requests',
    `${payroll}tax-relief-request.html`,
    'file',
  ),
  option(
    'payroll',
    'deduction',
    'Deduction Request',
    '扣款申请',
    'Submit a payroll deduction.',
    '提交薪资扣款申请。',
    'individual',
    'requests',
    `${payroll}deduction-request.html`,
    'file-plus',
  ),
  option(
    'payroll',
    'payslip',
    'Payslip',
    '工资单',
    'Monthly salary statements.',
    '每月薪资明细。',
    'individual',
    'records',
    `${payroll}payslip.html`,
    'wallet',
  ),
  option(
    'payroll',
    'ea',
    'EA',
    'EA 年度税务表',
    'Annual tax statement.',
    '年度税务报表。',
    'individual',
    'records',
    `${payroll}ea-form.html`,
    'file',
  ),
  option(
    'payroll',
    'history',
    'History',
    '历史记录',
    'Payroll activity records.',
    '薪资活动记录。',
    'individual',
    'records',
    `${payroll}history.html`,
    'history',
  ),
  option(
    'payroll',
    'tax-relief',
    'Tax Relief',
    '税务减免',
    'Review and approve staff tax relief claims.',
    '查看并审批员工税务减免申请。',
    'team',
    'approvals',
    `${payroll}tax-relief.html`,
    'file',
  ),
  option(
    'payroll',
    'pending',
    'Pending Approval',
    '待审批',
    'Tax relief and deduction requests awaiting review.',
    '待审批的税务减免与扣款申请。',
    'team',
    'approvals',
    `${payroll}pending-approval.html`,
    'check',
  ),

  option(
    'employee-career',
    'feedback',
    'Feedback',
    '反馈',
    'Submit employee feedback and review its history.',
    '提交员工反馈并查看历史。',
    'individual',
    'requests',
    `${career}individual/feedback.html`,
    'message',
  ),
  option(
    'employee-career',
    'whereabout',
    'Whereabout',
    '行踪',
    'Record your location, dates and whereabouts.',
    '记录个人地点、日期与行踪。',
    'individual',
    'requests',
    `${career}individual/whereabout.html`,
    'pin',
  ),
  option(
    'employee-career',
    'my-event',
    'My Event',
    '个人事项',
    'Submit and review your employee events.',
    '提交并查看个人员工事项。',
    'individual',
    'requests',
    `${career}individual/my-event.html`,
    'calendar',
  ),
  option(
    'employee-career',
    'history',
    'History',
    '历史记录',
    'Feedback, whereabouts and employee event history.',
    '反馈、行踪与员工事项历史。',
    'individual',
    'records',
    `${career}history.html`,
    'history',
  ),
  option(
    'employee-career',
    'onboard-activity',
    'Onboard Activity',
    '入职活动',
    'Onboarding activity information.',
    '个人入职活动资料。',
    'individual',
    'planning',
    `${career}individual/onboard-activity.html`,
    'clipboard',
  ),
  option(
    'employee-career',
    'confirm-new-user',
    'Confirm New User',
    '确认新用户',
    'Review new users and their confirmation details.',
    '查看新用户与确认详情。',
    'team',
    'approvals',
    `${career}team/confirm-new-user.html`,
    'user-check',
  ),
  option(
    'employee-career',
    'staff-list',
    'Staff List',
    '员工列表',
    'Staff directory, employee cards and profile information.',
    '员工通讯录、员工卡片与资料。',
    'team',
    'information',
    `${career}team/staff-list.html`,
    'users',
  ),
  option(
    'employee-career',
    'manpower-stats',
    'Manpower Stats',
    '人力统计',
    'Review headcount and manpower statistics.',
    '查看人数与人力统计。',
    'team',
    'reports',
    `${career}team/manpower-stats.html`,
    'chart',
  ),
  option(
    'employee-career',
    'confirm-staff',
    'Confirm Staff',
    '员工转正',
    'Staff confirmation reviews and decisions.',
    '员工转正评估与决定。',
    'team',
    'approvals',
    `${career}team/confirm-staff.html`,
    'user-check',
  ),
  option(
    'employee-career',
    'staff-exit',
    'Staff Exit',
    '员工离职',
    'Review staff exits and exit details.',
    '查看员工离职与详情。',
    'team',
    'records',
    `${career}team/staff-exit.html`,
    'users',
  ),
  option(
    'employee-career',
    'staff-request',
    'Staff Request',
    '员工申请',
    'Manage staff requests and their workflows.',
    '管理员工申请与审批流程。',
    'team',
    'requests',
    `${career}team/staff-request.html`,
    'file-plus',
  ),
  option(
    'employee-career',
    'staff-attrition',
    'Staff Attrition',
    '员工流失',
    'Review staff attrition indicators and analysis.',
    '查看员工流失指标与分析。',
    'team',
    'reports',
    `${career}team/staff-attrition.html`,
    'chart',
  ),
  option(
    'employee-career',
    'staff-retention',
    'Staff Retention',
    '员工留任',
    'Review staff retention information and analysis.',
    '查看员工留任资料与分析。',
    'team',
    'reports',
    `${career}team/staff-retention.html`,
    'users',
  ),
  option(
    'employee-career',
    'staff-whereabout',
    'Staff Whereabout',
    '员工行踪',
    'Review staff whereabouts and location records.',
    '查看员工行踪与地点记录。',
    'team',
    'records',
    `${career}team/staff-whereabout.html`,
    'pin',
  ),
  option(
    'employee-career',
    'staff-events',
    'Staff Events',
    '员工事项',
    'Review employee events across the team.',
    '查看团队员工事项。',
    'team',
    'records',
    `${career}team/staff-events.html`,
    'calendar',
  ),
  option(
    'employee-career',
    'staff-feedback',
    'Staff Feedback',
    '员工反馈',
    'Review staff feedback records and responses.',
    '查看员工反馈记录与回复。',
    'team',
    'records',
    `${career}team/staff-feedback.html`,
    'message',
  ),
  option(
    'employee-career',
    'key-staff-nomination',
    'Key Staff Nomination',
    '关键员工提名',
    'Nominate and review key staff.',
    '提名与查看关键员工。',
    'team',
    'requests',
    `${career}team/key-staff-nomination.html`,
    'award',
  ),
  option(
    'employee-career',
    'staff-engagement',
    'Staff Engagement',
    '员工参与度',
    'Staff engagement information.',
    '员工参与度资料。',
    'team',
    'reports',
    `${career}team/staff-engagement.html`,
    'users',
  ),
  option(
    'employee-career',
    'staff-onboard',
    'Staff Onboard',
    '员工入职',
    'Staff onboarding information.',
    '员工入职资料。',
    'team',
    'planning',
    `${career}team/staff-onboard.html`,
    'user-check',
  ),

  option(
    'project-task',
    'work-plan',
    'Work Plan',
    '工作计划',
    'Plan project work, dates, tasks and supporting details.',
    '安排项目工作、日期、任务与相关资料。',
    'individual',
    'planning',
    `${project}work-plan.html`,
    'clipboard',
  ),
  option(
    'project-task',
    'time-sheet',
    'Time Sheet',
    '工时表',
    'Record project activities, normal hours and OT hours.',
    '记录项目活动、正常工时与加班工时。',
    'individual',
    'requests',
    `${project}time-sheet.html`,
    'clock',
  ),
  option(
    'project-task',
    'history',
    'History',
    '历史记录',
    'Submitted, resubmit, draft and overdue work records.',
    '已提交、需重新提交、草稿与逾期工作记录。',
    'individual',
    'records',
    `${project}history.html`,
    'history',
  ),
  option(
    'project-task',
    'calendar',
    'My Work Calendar',
    '个人工作日历',
    'Work plans and timesheet activities by date.',
    '按日期查看工作计划与工时表活动。',
    'individual',
    'planning',
    'modules/project-task/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'project-task',
    'work-assignment',
    'Work Assignment',
    '工作分配',
    'Assign project work, staff and task details.',
    '分配项目工作、员工与任务详情。',
    'team',
    'planning',
    `${project}work-assignment.html`,
    'briefcase',
  ),
  option(
    'project-task',
    'timesheet-highlight',
    'Timesheet Highlight',
    '工时表重点',
    'Review project and staff timesheet indicators.',
    '查看项目与员工工时表指标。',
    'team',
    'reports',
    `${project}timesheet-highlight.html`,
    'chart',
  ),
  option(
    'project-task',
    'pending-approval',
    'Pending Approval',
    '待审批',
    'Review timesheets awaiting approval.',
    '审批待处理的工时表。',
    'team',
    'approvals',
    `${project}pending-approval.html`,
    'check',
  ),
  option(
    'project-task',
    'current-project',
    'Current Project',
    '当前项目',
    'Current project overview, tasks and project details.',
    '当前项目概览、任务与项目详情。',
    'team',
    'information',
    'modules/project-task/index.html?webView=details&scope=team',
    'briefcase',
  ),

  option(
    'admin',
    'news',
    'News',
    '公告',
    'Company news, announcements and article details.',
    '公司新闻、公告与文章详情。',
    'individual',
    'information',
    `${workplace}news.html`,
    'file',
  ),
  option(
    'admin',
    'book-resource',
    'Book Resource',
    '预约资源',
    'Choose resources, dates and booking details.',
    '选择资源、日期与预约详情。',
    'individual',
    'requests',
    `${workplace}book-resource.html`,
    'calendar',
  ),
  option(
    'admin',
    'letter-request',
    'Letter Request',
    '信件申请',
    'Request HR letters with the required information.',
    '填写所需资料以申请人事信件。',
    'individual',
    'requests',
    `${workplace}letter-request.html`,
    'file-plus',
  ),
  option(
    'admin',
    'guest-visit',
    'Guest Visit',
    '访客登记',
    'Visitor details, visit schedules and visit requests.',
    '访客资料、来访时间与来访申请。',
    'individual',
    'requests',
    `${workplace}guest-visit.html`,
    'user-check',
  ),
  option(
    'admin',
    'inventory-request',
    'Inventory Request',
    '物品申请',
    'Select inventory items, quantities and request details.',
    '选择物品、数量与申请详情。',
    'individual',
    'requests',
    `${workplace}inventory-request.html?scope=individual`,
    'package',
  ),
  option(
    'admin',
    'policy-sop',
    'Policy / SOP',
    '政策与标准流程',
    'Read company policies and standard operating procedures.',
    '阅读公司政策与标准作业流程。',
    'individual',
    'information',
    `${workplace}policy-sop.html`,
    'shield',
  ),
  option(
    'admin',
    'history',
    'History',
    '历史记录',
    'Resource, letter, visitor and inventory request history.',
    '资源、信件、访客与物品申请历史。',
    'individual',
    'records',
    `${workplace}history.html`,
    'history',
  ),
  option(
    'admin',
    'calendar',
    'Calendar',
    '日历',
    'Workplace bookings, visits and scheduled events.',
    '行政资源预约、来访与日程事项。',
    'individual',
    'planning',
    'modules/admin/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'admin',
    'pending-approval',
    'Pending Approval',
    '待审批',
    'Workplace requests awaiting review.',
    '待审批的行政申请。',
    'team',
    'approvals',
    `${workplace}pending-approval.html?scope=team`,
    'check',
  ),
  option(
    'admin',
    'asset-highlight',
    'Asset Highlight',
    '资产重点',
    'Review resource and asset information.',
    '查看资源与资产资料。',
    'team',
    'reports',
    `${workplace}asset-highlight.html?scope=team`,
    'package',
  ),

  option(
    'profile',
    'work',
    'Work',
    '工作资料',
    'Employee ID, appointment, department and employment details.',
    '员工编号、职位、部门与任职详情。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-work',
    'briefcase',
  ),
  option(
    'profile',
    'personal',
    'Personal & Family',
    '个人与家庭',
    'Personal particulars, spouse, children and family information.',
    '个人资料、配偶、子女与家庭信息。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-personal',
    'user',
  ),
  option(
    'profile',
    'contact',
    'Contact & Address',
    '联系方式与地址',
    'Contact numbers, addresses and emergency contacts.',
    '电话号码、地址与紧急联系人。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-contact',
    'pin',
  ),
  option(
    'profile',
    'qualification',
    'Qualification',
    '学历与资格',
    'Education and qualification records.',
    '教育与资格记录。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-education',
    'award',
  ),
  option(
    'profile',
    'payroll',
    'Payroll & Tax',
    '薪资与税务',
    'Bank, statutory, payroll and tax information.',
    '银行、法定缴纳、薪资与税务资料。',
    'individual',
    'information',
    'me.html?webView=details&scroll=bento-finance',
    'wallet',
  ),
  option(
    'profile',
    'career',
    'Career',
    '职业经历',
    'Career and employment history.',
    '职业与任职历史。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-career',
    'briefcase',
  ),
  option(
    'profile',
    'performance',
    'Performance',
    '绩效',
    'Performance assessments and their details.',
    '绩效评估与详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-performance',
    'chart',
  ),
  option(
    'profile',
    'competencies',
    'Competencies',
    '能力',
    'Competency assessments and recorded skills.',
    '能力评估与技能记录。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-competency',
    'award',
  ),
  option(
    'profile',
    'training',
    'Training',
    '培训',
    'Training courses, dates and training records.',
    '培训课程、日期与记录。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-training',
    'book',
  ),
  option(
    'profile',
    'assets',
    'Assets',
    '资产',
    'Assigned assets and custody details.',
    '领用资产与保管详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-assets',
    'package',
  ),
  option(
    'profile',
    'hr-letters',
    'HR Letters',
    '人事信件',
    'HR letters and letter document details.',
    '人事信件与文件详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-letters',
    'file',
  ),
  option(
    'profile',
    'disciplinary',
    'Disciplinary',
    '纪律记录',
    'Disciplinary records and related details.',
    '纪律记录与相关详情。',
    'individual',
    'records',
    'me.html?webView=details&scroll=bento-compliance',
    'shield',
  ),
  option(
    'profile',
    'view-jd',
    'View JD',
    '查看岗位说明',
    'Your job description, responsibilities and requirements.',
    '个人岗位说明、职责与要求。',
    'individual',
    'information',
    'me.html?webView=details&webAction=profile-jd',
    'file',
  ),
  option(
    'profile',
    'bonus-history',
    'Bonus History',
    '奖金历史',
    'Historical bonus payments and their details.',
    '往期奖金与明细。',
    'individual',
    'records',
    'bonus-history.html',
    'wallet',
  ),
  option(
    'profile',
    'salary-history',
    'Salary History',
    '薪资历史',
    'Salary changes and historical salary records.',
    '薪资调整与往期薪资记录。',
    'individual',
    'records',
    'salary-history.html',
    'history',
  ),
  option(
    'profile',
    'change-request',
    'Change Request',
    '资料更改申请',
    'Request changes to personal and employment information.',
    '申请修改个人与任职资料。',
    'individual',
    'requests',
    'change-request.html',
    'file-plus',
  ),
  option(
    'profile',
    'work-behaviour',
    'Work Behaviour Trend',
    '工作行为趋势',
    'Work behaviour indicators and trends.',
    '工作行为指标与趋势。',
    'individual',
    'reports',
    'work-behaviour.html',
    'chart',
  ),
  option(
    'profile',
    'subordinates',
    'Subordinates',
    '下属员工',
    'Review your reporting staff and their information.',
    '查看直属员工与相关资料。',
    'team',
    'information',
    'subordinates.html',
    'users',
  ),
];

/** Shared options appear in either scope; omitting scope returns the whole module. */
export function getModuleOptions(moduleId: string, scope?: ModuleScope): ModuleOption[] {
  return moduleNavigation.filter(
    (item) =>
      item.moduleId === moduleId && (!scope || item.scope === scope || item.scope === 'shared'),
  );
}
