import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

const project = 'modules/project-task/options/';

/** Original project-task option labels, scopes, order and business URLs. */
export const projectTaskNavigation: ModuleOption[] = [
  option(
    'project-task',
    'work-plan',
    'Work Plan',
    '工作计划',
    'Plan project work, dates, tasks and supporting details.',
    '安排项目工作、日期、任务与相关资料。',
    'individual',
    'planning',
    `${project}work-plan.html`,
    'clipboard',
  ),
  option(
    'project-task',
    'time-sheet',
    'Time Sheet',
    '工时表',
    'Record project activities, normal hours and OT hours.',
    '记录项目活动、正常工时与加班工时。',
    'individual',
    'requests',
    `${project}time-sheet.html`,
    'clock',
  ),
  option(
    'project-task',
    'history',
    'History',
    '历史记录',
    'Submitted, resubmit, draft and overdue work records.',
    '已提交、需重新提交、草稿与逾期工作记录。',
    'individual',
    'records',
    `${project}history.html`,
    'history',
  ),
  option(
    'project-task',
    'calendar',
    'My Work Calendar',
    '个人工作日历',
    'Work plans and timesheet activities by date.',
    '按日期查看工作计划与工时表活动。',
    'individual',
    'planning',
    'modules/project-task/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'project-task',
    'work-assignment',
    'Work Assignment',
    '工作分配',
    'Assign project work, staff and task details.',
    '分配项目工作、员工与任务详情。',
    'team',
    'planning',
    `${project}work-assignment.html`,
    'briefcase',
  ),
  option(
    'project-task',
    'timesheet-highlight',
    'Timesheet Highlight',
    '工时表重点',
    'Review project and staff timesheet indicators.',
    '查看项目与员工工时表指标。',
    'team',
    'reports',
    `${project}timesheet-highlight.html`,
    'chart',
  ),
  option(
    'project-task',
    'pending-approval',
    'Pending Approval',
    '待审批',
    'Review timesheets awaiting approval.',
    '审批待处理的工时表。',
    'team',
    'approvals',
    `${project}pending-approval.html`,
    'check',
  ),
  option(
    'project-task',
    'current-project',
    'Current Project',
    '当前项目',
    'Current project overview, tasks and project details.',
    '当前项目概览、任务与项目详情。',
    'team',
    'information',
    'modules/project-task/index.html?webView=details&scope=team',
    'briefcase',
  ),
];
