const fs = require('node:fs/promises');
const path = require('node:path');
const { cases } = require('./capture_detail_dialog_audit.cjs');
const output = path.join(__dirname, 'detail-popout-verification');
const escape = value => String(value).replace(/[&<>"']/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
(async () => {
  const results = JSON.parse(await fs.readFile(path.join(output, 'results.json'), 'utf8'));
  if (results.length !== 92 || results.some(result => result.error)) throw new Error('A passing full dark/light run is required before publishing the gallery.');
  await Promise.all(results.flatMap(result => [result.image, result.bottomImage].filter(Boolean)).map(file => fs.access(path.join(output, file))));
  await Promise.all(cases.map((job, offset) => fs.access(path.join(output, '..', 'detail-dialog-audit', String(offset + 1).padStart(2,'0') + '.png'))));
  const cards = cases.map((job, offset) => {
    const index = offset + 1;
    const images = ['dark','light'].map(theme => {
      const result = results.find(item => item.key === `${index}:${theme}`);
      return `<figure data-theme="${theme}"><figcaption>${theme === 'dark' ? '深色' : '浅色'} · 修改后</figcaption><a href="${result.image}"><img loading="lazy" src="${result.image}" alt="${escape(job.group + ' ' + job.name)}"></a>${result.bottomImage ? `<details><summary>查看底部 / 附件</summary><a href="${result.bottomImage}"><img loading="lazy" src="${result.bottomImage}" alt="详情底部与附件"></a></details>` : ''}</figure>`;
    }).join('');
    return `<article data-group="${escape(job.group)}"><h2>${index}. ${escape(job.group)} · ${escape(job.name)}</h2><p>${escape(job.file)}</p><div class="comparison"><figure class="before"><figcaption>修改前</figcaption><a href="../detail-dialog-audit/${String(index).padStart(2,'0')}.png"><img loading="lazy" src="../detail-dialog-audit/${String(index).padStart(2,'0')}.png" alt="修改前"></a></figure>${images}</div></article>`;
  }).join('');
  const groups = [...new Set(cases.map(job => job.group))];
  await fs.writeFile(path.join(output, 'gallery.html'), `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>46 个 View Details 设计核对</title><style>*{box-sizing:border-box}body{margin:0;padding:24px;background:#0b0b14;color:#eee;font-family:system-ui,sans-serif}h1{font-size:25px;margin:0 0 12px}header p{color:#bbb;max-width:900px;line-height:1.6}nav{display:flex;gap:16px;flex-wrap:wrap;align-items:center;margin:22px 0}select{background:#221a35;color:white;border:1px solid #6c5089;padding:8px;border-radius:8px}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,360px),1fr));gap:24px}article{background:#151523;padding:16px;border:1px solid #333344;border-radius:14px}h2{font-size:14px;margin:0;line-height:1.5}article p{font-size:11px;color:#aaa;overflow-wrap:anywhere}figure{margin:0;min-width:0}figcaption{color:#c4b5fd;font-size:12px;margin-bottom:10px}img{display:block;width:100%;max-width:380px;margin:auto;border-radius:10px}a{color:#c4b5fd}details{margin-top:12px}summary{cursor:pointer;color:#c4b5fd;font-size:12px}details img{margin-top:12px}.comparison{display:grid;gap:16px}.before,[data-theme=light]{display:none}body.light [data-theme=dark]{display:none}body.light [data-theme=light]{display:block}body.compare .before{display:block}body.compare .comparison{grid-template-columns:1fr 1fr}article[hidden]{display:none}body.compare main{grid-template-columns:repeat(auto-fit,minmax(min(100%,700px),1fr))}</style><header><h1>46 个 View Details · 设计核对</h1><p>统一为居中弹窗：紫色 header、宽度、透明度、两列字段与滚动样式。原有字段、固定数据及附件链接保留；附件保留在各自 tab/table 的末行，不另建 table。Approver Action Comments 统一为最下方的圆角卡片，位于审批按钮上方。原有三按钮保留三个；Deduction Request 按要求保留 Approve、Reject 两个。</p><p>深色 / 浅色 92 项逐项核对通过。点击图片可查看原尺寸；长表格可展开查看底部与附件。</p><nav><label>主题 <select id="theme"><option value="dark">深色</option><option value="light">浅色</option></select></label><label><input id="compare" type="checkbox"> 对照修改前</label><label>模块 <select id="group"><option value="">全部 46 个入口</option>${groups.map(group=>`<option>${escape(group)}</option>`).join('')}</select></label></nav></header><main>${cards}</main><script>document.getElementById('theme').onchange=e=>document.body.classList.toggle('light',e.target.value==='light');document.getElementById('compare').onchange=e=>document.body.classList.toggle('compare',e.target.checked);document.getElementById('group').onchange=e=>document.querySelectorAll('article').forEach(card=>card.hidden=!!e.target.value&&card.dataset.group!==e.target.value);</script></html>`);
  console.log('Gallery: scratch/detail-popout-verification/gallery.html');
})().catch(error => { console.error(error); process.exitCode = 1; });
