const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const storage = new Map();
const localStorage = { getItem: key => storage.get(key) || null, setItem: (key, value) => storage.set(key, value) };
const context = { window: {}, localStorage, crypto: require('node:crypto').webcrypto, Date };
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.resolve(__dirname, '../modules/admin/js/workplace-history-store.js'), 'utf8'), context);
const store = context.window.WorkplaceHistoryStore;
assert.equal(store.list().length, 0);
const letter = store.save({ kind: 'letter-request', title: 'Employment Confirmation', date: '2026-10-07', fields: [['Reason', '<script>test</script>']] });
assert.equal(letter.status, 'submitted');
assert.ok(letter.id);
store.save({ kind: 'guest-visit', title: 'Head Office', date: '2026-10-08', fields: [['Guests', 'Jane']] });
assert.equal(store.list().length, 2);
assert.equal(store.counts().submitted, 2);
assert.equal(store.counts().approved, 0);
const key = 'peoplehcm:workplace:history:v1';
const persisted = JSON.parse(storage.get(key));
storage.set(key, JSON.stringify([...persisted, { ...letter, id: 'invalid-fields', fields: [null] }, { ...letter, id: 'invalid-values', fields: [[null, 123]] }]));
assert.equal(store.list().length, 2, 'Malformed stored fields cannot reach the renderer');
assert.throws(() => store.save({ kind: 'news', title: 'Wrong category' }));
assert.equal(store.list().length, 2);
const saved = store.list();
saved[0].title = 'Changed outside the store';
assert.notEqual(store.list()[0].title, saved[0].title, 'Read returns independent data');
const reload = { window: {}, localStorage, crypto: context.crypto, Date };
vm.createContext(reload);
vm.runInContext(fs.readFileSync(path.resolve(__dirname, '../modules/admin/js/workplace-history-store.js'), 'utf8'), reload);
assert.equal(reload.window.WorkplaceHistoryStore.list().length, 2, 'Records survive navigation and reload');
const before = JSON.stringify(store.list());
localStorage.setItem = () => { throw new Error('Quota exhausted'); };
assert.throws(() => store.save({ kind: 'letter-request', title: 'Failed save', date: '2026-10-07', fields: [] }), /Quota exhausted/);
assert.equal(JSON.stringify(store.list()), before, 'Failed writes never claim a saved record');
console.log('PASS Workplace History store: allowed categories, persistence, counts and write failures');
