const assert = require('node:assert/strict');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const puppeteer = require('puppeteer');
const url = (file, theme) => pathToFileURL(path.resolve(__dirname, '../modules/admin/' + file)).href + '?theme=' + theme;
(async () => {
  const browser = await puppeteer.launch({ headless: true, executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', args: ['--allow-file-access-from-files'] });
  try {
    for (const theme of ['light', 'dark']) for (const width of [360, 420]) {
      const page = await browser.newPage();
      const errors = [];
      page.on('pageerror', error => errors.push(error.message));
      await page.setViewport({ width, height: 950 });
      await page.goto(url('index.html', theme), { waitUntil: 'domcontentloaded' });
      await page.evaluate(() => localStorage.removeItem('peoplehcm:workplace:history:v1'));
      await page.reload({ waitUntil: 'domcontentloaded' });
      assert.equal(await page.$$eval('[data-document-status]', nodes => nodes.length), 4);
      assert.deepEqual(await page.$$eval('.admin-option-title', nodes => nodes.map(node => node.textContent)), ['News', 'Book Resource', 'Letter Request', 'Guest Visit', 'Policy / SOP', 'History']);
      await page.screenshot({ path: path.resolve(__dirname, `workplace-document-status-${theme}-${width}.png`) });
      for (const status of ['submitted', 'resubmit', 'approved', 'rejected']) {
        await page.click(`[data-document-status="${status}"]`);
        await page.waitForSelector('#workplaceHistoryList');
        assert.equal(new URL(page.url()).searchParams.get('theme'), theme);
        assert.deepEqual(await page.$$eval('[data-history-kind]', nodes => nodes.map(node => node.textContent)), ['Guest Visit', 'Letter Request']);
        await page.click('[data-admin-back]');
        await page.waitForSelector('#workplaceDocumentStatus');
      }
      await page.goto(url('options/letter-request.html', theme), { waitUntil: 'domcontentloaded' });
      await page.click('#letterRequestSubmit');
      assert.equal(await page.evaluate(() => window.WorkplaceHistoryStore.list().length), 0, 'Invalid submissions cannot enter History');
      await page.select('#letterRequestType', 'employment-confirmation');
      await page.type('#letterRequestDescription', 'Bank application');
      await page.type('#letterRequestReason', '<script>unsafe()</script>');
      await page.$eval('#letterRequestRemarks', node => { node.value = 'Long remarks\n'.repeat(150); });
      await page.click('#letterRequestSubmit');
      assert.match(await page.$eval('#letterRequestFeedback', node => node.textContent), /saved to History/);
      await page.click('#letterRequestSubmit');
      assert.equal(await page.evaluate(() => window.WorkplaceHistoryStore.list().length), 1, 'Repeated Submit updates the same request');
      await page.goto(url('index.html', theme), { waitUntil: 'domcontentloaded' });
      assert.equal(await page.$eval('[data-document-status="submitted"] strong', node => node.textContent), '1');
      await page.click('[data-option-id="history"]');
      await page.waitForSelector('#workplaceHistoryList');
      await page.click('[data-history-kind="letter-request"]');
      assert.equal(await page.$$eval('#workplaceHistoryList .history-card-item', nodes => nodes.length), 1);
      await page.click('[data-record-id]');
      assert.match(await page.$eval('#historyDetailBody', node => node.textContent), /Bank application/);
      assert.equal(await page.$$eval('#historyDetailBody script', nodes => nodes.length), 0, 'Render saved text safely');
      await page.keyboard.press('Tab');
      assert.equal(await page.evaluate(() => document.activeElement.id), 'historyDetailBody', 'Details must be keyboard scrollable');
      await page.keyboard.press('PageDown');
      await page.waitForFunction(() => document.getElementById('historyDetailBody').scrollTop > 0);
      await page.keyboard.press('Tab');
      assert.equal(await page.evaluate(() => document.activeElement.id), 'closeHistoryDetails', 'Details focus remains inside the dialog');
      await page.keyboard.press('Escape');
      await page.click('#historyFilterTrigger');
      await page.select('#historyStatus', 'approved');
      await page.click('#applyHistoryFilter');
      assert.equal(await page.$eval('#historyEmptyState', node => node.hidden), false);
      await page.click('#historyFilterTrigger');
      await page.click('#resetHistoryFilter');
      await page.click('#closeHistoryFilter');
      assert.equal(await page.$$eval('#workplaceHistoryList .history-card-item', nodes => nodes.length), 1);
      await page.screenshot({ path: path.resolve(__dirname, `workplace-history-letter-${theme}-${width}.png`) });
      await page.goto(url('options/guest-visit.html', theme), { waitUntil: 'domcontentloaded' });
      await page.evaluate(() => localStorage.removeItem('peoplehcm:guest-visit:draft:v1'));
      await page.reload({ waitUntil: 'domcontentloaded' });
      await page.$eval('#visitTotalGuest', node => { node.value = '1'; });
      await page.$eval('#visitStartTime', node => { node.value = '09:00'; });
      await page.$eval('#visitEndTime', node => { node.value = '10:00'; });
      await page.select('#visitLocation', 'head-office');
      await page.click('#visitTab-guest');
      await page.click('#visitOpenGuest');
      await page.type('#visitGuestCompany', 'Acme');
      await page.select('#visitGuestRelation', 'customer');
      await page.type('#visitGuestName', 'Jane');
      await page.type('#visitGuestPosition', 'Manager');
      await page.click('#visitGuestAdd');
      await page.click('#visitTab-attendee');
      await page.click('#visitOpenAttendee');
      await page.select('#visitStaff', 'EBB01');
      await page.click('#visitAttendeeAdd');
      await page.click('#visitTab-other');
      await page.click('#visitSubmit');
      assert.match(await page.$eval('#visitFeedback', node => node.textContent), /saved to History/);
      await page.goto(url('index.html', theme), { waitUntil: 'domcontentloaded' });
      assert.equal(await page.$eval('[data-document-status="submitted"] strong', node => node.textContent), '2');
      await page.click('[data-option-id="history"]');
      await page.waitForSelector('[data-record-id]');
      await page.click('[data-record-id]');
      assert.match(await page.$eval('#historyDetailBody', node => node.textContent), /Jane.*Aina Rahman/s);
      await page.keyboard.press('Escape');
      await page.screenshot({ path: path.resolve(__dirname, `workplace-history-guest-${theme}-${width}.png`) });
      assert.equal(await page.$eval('.main-content', node => node.scrollWidth > node.clientWidth), false);
      assert.deepEqual(errors, []);
      console.log(`PASS ${theme} ${width}: dashboard, both submissions, persistence, counts, history categories, details, status filter and theme`);
      await page.close();
    }
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
