import type { ModuleOption } from '../../shared/types/navigation.ts';
import { createModuleOption as option } from '../../shared/navigation/createModuleOption.ts';

const attendance = 'modules/attendance/options/';

/** Original attendance option labels, scopes, order and business URLs. */
export const attendanceNavigation: ModuleOption[] = [
  option(
    'attendance',
    'clocking',
    'Clocking',
    '打卡',
    'Clock in and out, including location and remarks.',
    '上班与下班打卡，填写地点与备注。',
    'individual',
    'requests',
    `${attendance}clocking.html`,
    'clock',
  ),
  option(
    'attendance',
    'attendance',
    'Attendance',
    '考勤',
    'Daily attendance, work hours and attendance advice.',
    '每日考勤、工作时数与考勤反馈。',
    'individual',
    'records',
    `${attendance}attendance.html`,
    'clipboard',
  ),
  option(
    'attendance',
    'overtime',
    'Overtime',
    '加班',
    'Overtime plans, final requests and history.',
    '加班计划、最终加班申请与历史。',
    'individual',
    'requests',
    `${attendance}overtime.html`,
    'timer',
  ),
  option(
    'attendance',
    'hours-summary',
    'Hours Summary',
    '时数汇总',
    'Review your work and overtime hours.',
    '查看个人工作与加班时数。',
    'individual',
    'reports',
    `${attendance}hours-summary.html`,
    'chart',
  ),
  option(
    'attendance',
    'history',
    'History',
    '历史记录',
    'Attendance requests, details and workflow status.',
    '考勤申请、详情与审批流程状态。',
    'individual',
    'records',
    `${attendance}history.html`,
    'history',
  ),
  option(
    'attendance',
    'feedback',
    'Pending Attendance Feedback',
    '待处理考勤反馈',
    'Review and respond to attendance feedback.',
    '查看并处理考勤反馈。',
    'individual',
    'requests',
    `${attendance}feedback-history.html`,
    'message',
  ),
  option(
    'attendance',
    'clocking-history',
    'Clocking History',
    '打卡记录',
    'Submitted, resubmit, approved and rejected clocking records.',
    '已提交、需重新提交、已批准与已拒绝的打卡记录。',
    'individual',
    'records',
    `${attendance}clocking-history.html`,
    'history',
  ),
  option(
    'attendance',
    'calendar',
    'My Schedule',
    '我的排班',
    'Your calendar, shift and overtime details.',
    '查看个人日历、班次与加班安排。',
    'individual',
    'planning',
    'modules/attendance/index.html?webView=details&scope=individual',
    'calendar',
  ),
  option(
    'attendance',
    'shift-plan',
    'Shift Plan',
    '排班计划',
    'Plan work shifts, leave and nonworking days.',
    '安排工作班次、请假与休息日。',
    'team',
    'planning',
    `${attendance}shift-plan.html`,
    'calendar',
  ),
  option(
    'attendance',
    'ot-plan',
    'OT Plan',
    '加班计划',
    'Plan staff overtime and review planned hours.',
    '安排员工加班并查看计划时数。',
    'team',
    'planning',
    `${attendance}ot-plan.html`,
    'timer',
  ),
  option(
    'attendance',
    'daily-ot',
    'Daily OT',
    '每日加班',
    'Review daily overtime and final OT details.',
    '查看每日加班与最终加班详情。',
    'team',
    'records',
    `${attendance}daily-ot.html`,
    'clock',
  ),
  option(
    'attendance',
    'daily-manpower',
    'Daily Manpower',
    '每日人力',
    'Scheduled, present, absent and overtime manpower.',
    '计划出勤、实际出勤、缺勤与加班人力。',
    'team',
    'reports',
    `${attendance}daily-manpower.html`,
    'users',
  ),
  option(
    'attendance',
    'work-hour-violation',
    'Work Hour Violation',
    '工时违规',
    'Review staff work hour violations.',
    '查看员工工时违规情况。',
    'team',
    'reports',
    `${attendance}work-hour-violation.html`,
    'shield',
  ),
  option(
    'attendance',
    'clocking-summary',
    'Clocking Summary',
    '打卡汇总',
    'Staff clocking and exception summaries.',
    '员工打卡与异常汇总。',
    'team',
    'reports',
    `${attendance}clocking-summary.html`,
    'clipboard',
  ),
  option(
    'attendance',
    'staff-attendance',
    'Staff Attendance',
    '员工考勤',
    'Review employee attendance records and details.',
    '查看员工考勤记录与详情。',
    'team',
    'records',
    `${attendance}staff-attendance.html`,
    'users',
  ),
  option(
    'attendance',
    'staff-hours-summary',
    'Staff Hours Summary',
    '员工时数汇总',
    'Staff work, overtime and leave hours.',
    '员工工作、加班与请假时数。',
    'team',
    'reports',
    `${attendance}staff-hours-summary.html`,
    'chart',
  ),
  option(
    'attendance',
    'attendance-highlight',
    'Attendance Highlight',
    '考勤重点',
    'Attendance indicators, trends and analysis.',
    '考勤指标、趋势与分析。',
    'team',
    'reports',
    `${attendance}attendance-highlight.html`,
    'chart',
  ),
  option(
    'attendance',
    'overtime-highlight',
    'Overtime Highlight',
    '加班重点',
    'Overtime indicators and staff analysis.',
    '加班指标与员工分析。',
    'team',
    'reports',
    `${attendance}overtime-highlight.html`,
    'chart',
  ),
  option(
    'attendance',
    'overtime-costing',
    'Overtime Costing',
    '加班成本',
    'Review overtime costs and breakdowns.',
    '查看加班成本与分类明细。',
    'team',
    'reports',
    `${attendance}overtime-costing.html`,
    'wallet',
  ),
  option(
    'attendance',
    'attendance-performance',
    'Attendance Performance',
    '考勤表现',
    'Staff attendance performance and trends.',
    '员工考勤表现与趋势。',
    'team',
    'reports',
    `${attendance}attendance-performance.html`,
    'chart',
  ),
  option(
    'attendance',
    'hours-costing',
    'Hours Costing',
    '工时成本',
    'Review work hour costs and breakdowns.',
    '查看工时成本与分类明细。',
    'team',
    'reports',
    `${attendance}hours-costing.html`,
    'wallet',
  ),
  option(
    'attendance',
    'pending-approval',
    'Pending Approval',
    '待审批',
    'OT Plan Request, Final OT Request and Attendance Feedback.',
    '加班计划申请、最终加班申请与考勤反馈。',
    'team',
    'approvals',
    `${attendance}team.html?webView=details&view=approvals&tab=ot_plan`,
    'check',
  ),
  option(
    'attendance',
    'verification',
    'Attendance Verification',
    '考勤核实',
    'Clocking exceptions and feedback audits.',
    '打卡异常与考勤反馈核查。',
    'team',
    'approvals',
    `${attendance}team.html?webView=details&view=verification`,
    'shield',
  ),
  option(
    'attendance',
    'team-overview',
    'Team Overview',
    '团队概览',
    'Scheduled to work, planned OT, present and no show.',
    '计划出勤、计划加班、实际出勤与未到岗员工。',
    'team',
    'information',
    `${attendance}team.html?webView=details&scope=team`,
    'users',
  ),
];
